INSERT INTO sales_pipeline_deals (id,opportunity_name,client,stage,probability,amount,weighted_amount,expected_close_date,bdm,estimator,project_manager,building_type,modules,notes,source_type,source_sheet,source_row) VALUES
('crm-row-133','Stella Elemantary Charter','St Bernadette Catholic','estimate',35,0,0,'2027-12-31','Frank',NULL,NULL,'(8) 24x40 & (1) 24x40 RR',0,'5/13 Proposals being reviewed. We''re competng with a dealer, not sure who','excel_import','Master Jobs',133),
('crm-row-134','Ventura Junior Fire Academy','Ventura County Fire Dept','lead',15,0,0,NULL,'Frank',NULL,NULL,'(1) 96x40 Classrooms',0,'5/21 Proposal sent to Art','excel_import','Master Jobs',134),
('crm-row-135','Big Bear HS Toilet Building','Bear Valley USD','lead',15,781495,117224,NULL,'Frank',NULL,NULL,'(1) 78''x 25''',0,'5/13 Proposal with BVP','excel_import','Master Jobs',135),
('crm-row-136','Enterprise HS Culinary Arts','Shasta UHSD','lead',15,0,0,'2027-07-01','Frank',NULL,NULL,'(1) 3,950 sf Culinary Building',0,'Bids on 5/28','excel_import','Master Jobs',136),
('crm-row-137','Highland ES','Pittsburg USD','lead',15,0,0,'2027-07-01','Frank',NULL,NULL,'(1) 156x40 & (1) 144x40',0,'Bids on 6/4','excel_import','Master Jobs',137),
('crm-row-138','Pacifica Graduate Institute','Pacifica Graduate Institute','estimate',35,0,0,'2027-01-01','Joe',NULL,NULL,'(1) 36x60 Classroom Office Building',0,'Kyle''s referral. Simeon Stewart will discuss internally with his team regarding going modular','excel_import','Master Jobs',138),
('crm-row-139','Lay Down','Southern California Edison','estimate',35,0,0,'2027-01-01','Joe',NULL,NULL,'(50) Office Buildings with various interior layouts',0,'SCE has over 50 Lay Down locations that will need office buildings.
Dumark is the GC. High vetting process.','excel_import','Master Jobs',139),
('crm-row-140','Fair Oaks','Southern California Edison','estimate',35,0,0,'2027-01-01','Joe',NULL,NULL,NULL,0,'Per Crysal Delgadillo, project is on hold','excel_import','Master Jobs',140),
('crm-row-141','Monterey Vista ES','Garvey SD','estimate',35,4494585.54,1573105,NULL,'Sandra',NULL,NULL,'(1) 144x40 Two Story Bldg with Two RR',0,'September 2026 discussions with Adela and a 2027 project.','excel_import','Master Jobs',141),
('crm-row-142','Midway Restroom Project','Orange Fair & Event Center','proposal',55,0,0,NULL,'Sandra',NULL,NULL,'(4) 12x40 TB',0,'Met with end user and shared piggyback documents 2/10/26 - who is doing proposal? Adela reaching out?','excel_import','Master Jobs',142)
ON CONFLICT (id) DO UPDATE SET opportunity_name=EXCLUDED.opportunity_name,client=EXCLUDED.client,stage=EXCLUDED.stage,probability=EXCLUDED.probability,amount=EXCLUDED.amount,weighted_amount=EXCLUDED.weighted_amount,expected_close_date=EXCLUDED.expected_close_date,bdm=EXCLUDED.bdm,project_manager=EXCLUDED.project_manager,building_type=EXCLUDED.building_type,notes=EXCLUDED.notes;